In [14]:
#show the dupliucated data
import pandas as pd
import numpy as np
#from  matplotlib import pyplot as plt
df=pd.read_csv('./movies_2.csv')
df[df.duplicated(['Title'], keep=False)]
df1=df.drop_duplicates()
df1[df1.duplicated(['Title'], keep=False)]

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
21,22,Teenage Mutant Ninja Turtles,PG,13500000.0,2.020000e+08,1990-03-30,Action,93.0,6.8,79806.0,Four teenage mutant ninja turtles emerge from ...
46,47,Beauty and the Beast,PG,25000000.0,3.773506e+08,1991-11-13,Animation,84.0,8.0,397467.0,A prince cursed to spend his days as a hideous...
65,66,Aladdin,G,28000000.0,5.040502e+08,1992-11-25,Animation,90.0,8.0,336384.0,A kindhearted street urchin and a power-hungry...
98,99,Jurassic Park III,PG-13,93000000.0,3.688000e+08,2001-07-16,Thriller,92.0,8.9,1690474.0,A decidedly odd couple with ulterior motives ...
107,108,The Lion King,G,45000000.0,7.882418e+08,1994-06-23,Animation,89.0,8.5,869127.0,A Lion cub crown prince is tricked by a treach...
195,196,Godzilla,PG-13,130000000.0,3.790143e+08,1998-05-20,Thriller,139.0,5.4,174600.0,"A giant, reptilian monster surfaces, leaving d..."
249,250,Jurassic Park III,PG-13,93000000.0,3.687808e+08,2001-07-18,Adventure,92.0,5.9,280110.0,A decidedly odd couple with ulterior motives c...
501,502,Teenage Mutant Ninja Turtles,PG-13,125000000.0,4.772000e+08,2014-08-07,Action,101.0,5.8,194073.0,"When a kingpin threatens New York City, a grou..."
504,505,Godzilla,PG-13,160000000.0,5.290761e+08,2014-05-14,Thriller,123.0,6.4,359438.0,The world is beset by the appearance of monstr...
565,566,Beauty and the Beast,PG,160000000.0,1.262886e+09,2017-03-16,Drama,129.0,NaN,NaN,NaN
609,610,Aladdin,PG,183000000.0,1.049000e+09,2019-05-08,Fantasy,128.0,NaN,NaN,NaN
613,614,The Lion King,PG,250000000.0,1.632000e+09,2019-07-09,Drama,118.0,NaN,NaN,NaN